### ISSUE TITLE
Alert cache

### ISSUE THREAD

**Issue by n3tsurge** [n3tsurge/elastic2hive#5]
Create an alert cache index so we don't attempt to push to TheHive over and over during the search window.

Cache timeout should be lookbacktime+1 minute

**Comment by n3tsurge** [comment]
+1 memcached

**Comment by SMAPPER** [comment]
I have memcached added and tested under the dev branch. I've tested only using elastalert. If for some reason it does not work with signals it will be because the unique identifier field needs to be changed.
